app-settings:
  name: dev
  api:
    key: bf16563b8b814066b3b4e7b6a0b35e4a
    host: https://api.sl.se/api2/linedata.json?key=${app-settings.api.key}
    line: ${app-settings.api.host}&model=line&DefaultTransportModeCode=BUS
    journeyPatterns: ${app-settings.api.host}&model=jour&DefaultTransportModeCode=BUS
    stopPoints: ${app-settings.api.host}&model=stop
    webclientDataBufferLimit: 50MB
    timeOutMs: 300000


logging:
  level:
    root: info
    '[org.springframework.boot]': info


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console: enabled=true
    console.path: /h2-console